config/routes.rb
Rails.application.routes.draw do
  
  get "products/trans"
  post "products/trans_pay"
  get "cart/order"

  get 'items' => 'items#index'

  devise_for :users

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  resources :products
   root 'products#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :product
  mount_uploader :image, ImageUploader

  def self.search(search)
  	where("item_for_rent LIKE ? OR brand LIKE ?", "%#{search}%", "%#{search}%") 
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :items
	mount_uploader :image, ImageUploader
	accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true
	validates :category, presence: true

	def self.search(search)
  	where("category LIKE ?", "%#{search}%") 
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 3..124
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
   before_action :authenticate_user!
  def add
		id = params[:id]
		if session[:cart] then
			cart = session[:cart] 
		else
			session[:cart] = {}
			cart = session[:cart]
		end
		
		if cart[id] then
			cart[id] = cart[id] + 1
		else
			cart[id] = 1
		end
		redirect_to :action => :index
	end 

		def order
		if session[:cart] then
  		@cart = session[:cart]
  	else
  		@cart = {}
    end
	end

def clearCart
		session[:cart] = nil
		redirect_to :action => :index
	end
	# helper_method :clearCart


  def index
  	if session[:cart] then
  		@cart = session[:cart]
  	else
  		@cart = {}
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
    @items = Item.paginate(page: params[:page], per_page: 20)
    if params[:search]
      @items = Item.search(params[:search]).paginate(page: params[:page])
    else
      @items = Item.paginate(page: params[:page], per_page: 20)
    end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @products = Product.all
    if params[:search]
    @products = Product.search(params[:search]).order("category ASC")
  else
    @products = Product.all
  end
  end

  def show
  end

  def new
    @product = Product.new
    @product.items.build
  end

  def edit
    @product.items.build
  end

  def create
    @product = Product.new(product_params)

      if @product.save
        redirect_to @product, notice: 'Product was successfully created.' 
      else
        render :new 
      end
  end
 

  def update
      if @product.update(product_params)
        redirect_to @product, notice: 'Product was successfully updated.' 
      else
        render :edit 
      end
  end

  def destroy
    @product.destroy
     redirect_to products_url, notice: 'Product was successfully destroyed.' 
  end

  def trans_pay
    
    #@item = Item.find params[:item_id]
    @result = Braintree::Transaction.sale(
    :amount => params[:cart_total],
    :credit_card => {
      :number => params[:credit_card_no],
      :expiration_date => "#{params['date']['exp_date(2i)']}/#{params['date']['exp_date(1i)']}"
    },
    :options=> {
                    store_in_vault: true
                  })
    if @result.success?
      current_user.update_columns(braintree_customer_id: @result.transaction.customer_details.id)
      redirect_to :action=>"order", :controller => "cart"
    else
      redirect_to :action=>"trans", notice: "Transaction fail"
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:category, :image, items_attributes: [:id,:brand, :rental_cost, :item_for_rent, :image, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<div class = "cart_page"><h1 class = "cart_page_h1">Your Cart</h1>
	<div>
		<span class= "cart-continue-shopping-btn btn btn-primary"><%=link_to "Continue Shopping", root_path%></span>
		<%if !@cart.empty?%>
			<%= link_to 'Empty your Cart', cart_clear_path%>
		<%end%>
	</div>

	<%@total = 0%>

	<div class ="row">
		<div class = "col col-md-8">
			<table>
				<tr class = "table_header">
					<th width = 100></th>
					<th width = 280></th>
					<th width = 100><span>Price</span></th>
					<th width = 80>Quantity</th>
				</tr>
				<%@cart.each do |id, quantity|%>
					<% item = Item.find_by_id(id)%>
					<tr >
						<td>
							<%= image_tag item.image.image.url, class: "thumb_image" %>
						</td>
						<td><h3><%= item.item_for_rent%><br>
							<%=item.brand%></h3>
						</td>
						<td align = "center" class = "price">
							<%= number_to_currency(item.rental_cost, :unit => 'INR ')%>
						</td>
						<td align = "center">
							<%=quantity%>
						</td>
					</tr>
					<% @total += quantity * item.rental_cost%>
				<%end%>
			</table><br><br>
			<p><b>Total cart Value: <%=number_to_currency(@total, unit: 'INR')%></b><p>
			<p><h4 class = "checkout-btn btn btn-success"><%=link_to "Proceed to Checkout", products_trans_path(:cart_total=>@total)%></h4>
		</div>

		<div class ="col col-md-4">
			<p class ="terms-reminder">Please check the <%=link_to "Terms and conditions", "#"%> of rental and return before proceeding</p>
			<div class = "cart-sidebar-orange-box">
				<p class = "cart_value"><b>Total Cart Value:: <%=number_to_currency(@total, unit: 'INR ')%></b><p>
				<p><h4 class = "checkout-btn btn btn-success"><%=link_to "Proceed to Checkout", products_trans_path(:cart_total=>@total)%></h4>
			</div>
		</div>
	</div>
</div>

app/views/cart/order.html.erb
<div class = "cart_page">
	<h1>"Congratulations!! Your order was placed successfully!"</h1>
	<h3 class = "cart_page_h1">Your Order Summary</h3>
	<%@total = 0%>

<div class ="row">
	<div class = "col col-md-8">
<table>
	<tr class = "table_header">
		<th width = 100></th>
		<th width = 280></th>
		<th width = 100><span>Price</span></th>
		<th width = 80>Quantity</th>
	</tr>
<%@cart.each do |id, quantity|%>
	<% item = Item.find_by_id(id)%>
	<tr >
		<td>
		<%= image_tag item.image.image.url, class: "thumb_image" %></td>
		<td><h3><%= item.item_for_rent%><br>
			<%=item.brand%></h3></td>
		<td align = "center" class = "price"><%= number_to_currency(item.rental_cost, :unit => 'INR ')%></td>
		<td align = "center"><%=quantity%></td>
		</tr>
		<% @total += quantity * item.rental_cost%>
<%end%>
</table><br><br>
<p><b>Total Order Value: <%=number_to_currency(@total, unit: 'INR')%></b><p>
</div>

	<div>
		<span class= "cart-continue-shopping-btn btn btn-primary"><%=link_to "Continue Shopping", root_path%></span>
	</div>

</div>
</div>

app/views/items/_search.html.erb
<% if @items.blank? %>
  <h4>There are no Items containing the term <%= params[:search] %>.</h4>
<% end %>

<%=form_tag(items_path, :method => 'get', id: "search-form") do %>	
<div class ="search-bar">
	<%= text_field_tag :search, params[:search], placeholder: "Search"%>
	</div>
	<%= submit_tag "Search", class: "fake-button"%>
<% end%>

<%if params[:search]%>
	<span class = "btn btn-info"><%=link_to "Back"%></span>
<%end%>

app/views/items/index.html.erb
<h1>All Items</h1>
<%= render 'items/search'%>
<table>
	<tr>
	<th></th>
	<th class = "item-list-header", width = 200 >Item</th>
	<th class = "item-list-header", width = 180>Brand</th>
	<th class = "item-list-header", width = 100>Price</th>
	<th class = "item-list-header", width = 100>Category</th>
</tr>
<%=will_paginate%>
<%@items.each do |i|%>

<tr class = "items-row">
	<td><%=image_tag i.image.image.url,   class: "item_index_image" %></td>
<td class = "centered item-index-list"><%= i.item_for_rent%></td>
<td class = "centered item-index-list"><%= i.brand%></td>
<td class = "centered item-index-list"><%= i.rental_cost%></td>
<td class = "centered item-index-list"><%= link_to Product.find(i.product_id).category, Product.find(i.product_id)%>
</td>

</tr>
<%end%>
</table>

app/views/layouts/_nav.html.erb
<div class= "nav navbar navbar-default">
	<div class= "container">
		<div class="navbar-brand">
			<%=link_to "Rent-All", root_path%>
		</div>
			<ul class= "nav navbar-nav navbar-right">
				<%if current_user == User.find_by(id: 1)%>
					<li><%=link_to "New Product", new_product_path%></li>
					<%end%>
				<li><%=link_to "All Products", products_path%></li>
				<li><%=link_to "All Items", items_path%></li>
				<%if user_signed_in?%>
				
				<li><%=link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
				<%else%>
				<li><%=link_to "Sign up", new_user_registration_path%></li>
				<li><%=link_to "Login", new_user_session_path%></li>
				<%end%>
				
			</ul>
		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rent All</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
	<body>
		<div class ="wrap-all">
			<%= render 'layouts/nav'%>
			<div class= "container">
				<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
        	<%= message %>
        </div>
      <% end %>

				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product, html: {mutipart: true} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-body">
    <div class ="row">
      <div class ="col col-md-6">
        <div id= "products">
          <%= f.input :category, input_html: {class: "form-control"} %>
          <%= f.label :image, "Add Image"%> <%= f.file_field :image%>
        </div>
      </div>
    
        
      <div class ="col col-md-6">
        <div id= "items">
          <%=f.simple_fields_for :items do |item|%>
            <%= render 'item_fields', f: item%>
            
              <%=link_to_add_association 'Add Item', f, :items, class: "btn btn-default"%>
            
          <%end%>
        </div>
        
        <p class= "submit"><%= f.button :submit,class: "btn btn-primary" %></p>
      
      </div>
      
    </div>
    

  </div>

<% end %>

app/views/products/_item_fields.html.erb
<div class = "clearfix">
	
		<%if @product.category == "Books"%>
			<%= f.input :item_for_rent, required: true, input_html: {class: "form-control"}%>
			<%= f.label :brand, "Author", input_html: {class: "form-control"}%>
			<%= f.input :brand, label: false, input_html: {class: "form-control"}%>
			<%= f.input :rental_cost,required: true, input_html: {class: "form-control"}%>
			<%= f.file_field :image, input_html: {class: "form-control"}%>
		<%else%>
			<%= f.input :item_for_rent, required: true, input_html: {class: "form-control"}%>
			<%= f.input :brand, input_html: {class: "form-control"}%>
			<%= f.input :rental_cost,required: true, input_html: {class: "form-control"}%>
			<%= f.label :image, "Add Image", input_html: {class: "form-control"}%>
			<%= f.file_field :image, input_html: {class: "form-control"}%>

		<%end%>
		</div>
		
		<p class= "submit"><%= link_to_remove_association "Remove", f,class: "btn btn-default" %>
		

app/views/products/_search.html.erb
<% if @products.blank? %>
  <h4>There are no Products containing the term <%= params[:search] %>.</h4>
<% end %>

<%=form_tag(products_path, :method => 'get', id: "search-form") do %>	
<div class ="search-bar">
	<%= text_field_tag :search, params[:search], placeholder: "Search"%>
	</div>
	<%= submit_tag "Search", class: "fake-button"%>
<% end%>

<%if params[:search]%>
	<span class = "btn btn-info"><%=link_to "Back"%></span>
<%end%>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render 'products/search'%>

<div class="products-index">
  <% @products.each do |product| %>
      <div class ="row first">
        <div class="col col-md-12">
          <div class ="row">
            <div class = "col col-md-6 category-name-index">
              <%= link_to product.category, product %>
            </div>

            <%if current_user == User.find(1)%>
            <div class ="col col-md-6 edit-button">
              <%= link_to(content_tag(:i,nil,class: 'fa fa-pencil-square-o'), edit_product_path(product)) %>
              <%= link_to(content_tag(:i,nil,class: 'fa fa-trash-o'), product, method: :delete, data: { confirm: 'Are you sure?' }) %>
            </div>
            <%end%>
          </div>

          <%= link_to  product  do %>
            <div class ="row each-product-row">
              <%product.items.each do |i|%>
                <div class="col col-md-2">
                  <%=image_tag i.image.image.url,   class: "item_image" %>
                  <br><span class = "item-name-index"><%=i.item_for_rent%></span><br>
                </div>
              <%end%>
            </div>
            <%end%>
        
        </div>
      </div>
    <% end %>
</div>
  

app/views/products/new.html.erb
<div class ="row">
	<div class ="col col-md-6 col-md-offset-3">
	<h1>Add new product</h1>
	</div>
</div>

<%= render 'form' %><br>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%if current_user == User.find(1)%>
	<div class ="row first">
	  <div class = "col col-md-6 category-name-index">
	  	<strong class = "category-name"><%= @product.category %></strong>
		</div>

		<div class ="col col-md-6 edit-button-show edit-button">
	 		 <%= link_to(content_tag(:i,nil,class: 'fa fa-pencil-square-o'), edit_product_path(@product)) %>
	  	<%= link_to(content_tag(:i,nil,class: 'fa fa-trash-o'), @product, method: :delete, data: { confirm: 'Are you sure?' }) %>
		</div>
	</div>
<%else%>
	<div class ="row first">
	  <div class = "col col-md-12 category-name-index">
	  	<strong class = "category-name"><%= @product.category %></strong><br><br>
	  </div>
	</div>
<%end%>

<div class ="row">
 	<%if (@product.category == "Books")%>
		<%@product.items.each do |i|%>
		<div class ="col col-md-3">
			<div class ="eachItem">
				<div class ="image-wrapper">
					<%= image_tag i.image.image.url %><br>
					<%=i.item_for_rent%> <br>
					Author:<%=i.brand%><br>
					Rent: Rs.<%= i.rental_cost%>  <a href="/cart/<%= i.id%>", class = "addtocart">Add to cart</a>
			</div>
			</div> 
			</div> 
		<%end%>
	<%else%>

		<%@product.items.each do |i|%>
		<div class ="col col-md-3">
			<div class ="eachItem">
				<div class ="image-wrapper">
			
					<%= image_tag i.image.image.url %><br>
					<%=i.item_for_rent%><br> 
					Brand:  <%=i.brand%><br>
					Rent: Rs.<%=i.rental_cost%>
			<a href="/cart/<%= i.id%>", class= "addtocart">Add to cart</a>
			</div>
			</div> 
			</div> 
		<%end%>
	<%end%>
</div>

<%if current_user == User.find(1)%>
	<div class ="edit-button-show">
    <%= link_to(content_tag(:i,nil,class: 'fa fa-pencil-square-o'), edit_product_path(@product)) %>
    <%= link_to(content_tag(:i,nil,class: 'fa fa-trash-o'), @product, method: :delete, data: { confirm: 'Are you sure?' }) %>
	</div>
<%end%>

app/views/products/trans.html.erb
  <div class ="row">
    <div class ="col col-md-6 col-md-offset-3 trans-form-p">
      <p>Please update Credit Card Details</p>
    </div>
  </div>

  <div class ="row trans-form">
    <div class = "col col-md-6 col-md-offset-3">
      <div class ="wrapper">
        <div class ="trans-pay-wrapper">
          <div class = "row">
            <div class="col col-md-10 col-md-offset-1 trans-pay-fields">
              <%= form_tag action: :trans_pay, :cart_total => params[:cart_total] , method: :post do %>
              <%= label_tag :Cardholder_name%>
              <%= text_field_tag :Cardholder_name, nil, required: true, autofocus: true, class: 'form-control'%><br>
      
      
              <%= label_tag :credit_card_no%>
              <%= text_field_tag :credit_card_no,nil, required: true, class: 'form-control'%><br>
                    
              <%= label_tag :csv%>
              <%= text_field_tag :csv,nil, required: true, class: 'form-control'%><br>
          
              <%= label_tag :expiry_date%><br>
              <%= date_select :date, :exp_date, :order=>[:month, :year]%><br><br>
                            
              <p><%= submit_tag "Make Payment", class: " trans-btn btn btn-primary form-control"%></p>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>